[colors.bright]
black = "0x969896"
blue = "0x3971ed"
cyan = "0x3971ed"
green = "0x198844"
magenta = "0xa36ac7"
red = "0xcc342b"
white = "0xffffff"
yellow = "0xfba922"

[colors.normal]
black = "0x1d1f21"
blue = "0x3971ed"
cyan = "0x3971ed"
green = "0x198844"
magenta = "0xa36ac7"
red = "0xcc342b"
white = "0xc5c8c6"
yellow = "0xfba922"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[font]
size = 10
