font:
  size: 10
colors:
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'
  normal:
    black:   '0x1d1f21'
    red:     '0xcc342b'
    green:   '0x198844'
    yellow:  '0xfba922'
    blue:    '0x3971ed'
    magenta: '0xa36ac7'
    cyan:    '0x3971ed'
    white:   '0xc5c8c6'
  bright:
    black:   '0x969896'
    red:     '0xcc342b'
    green:   '0x198844'
    yellow:  '0xfba922'
    blue:    '0x3971ed'
    magenta: '0xa36ac7'
    cyan:    '0x3971ed'
    white:   '0xffffff'
