#!/bin/bash

yay -Syu \
		alsa-utils \
		bluez \
		bluez-utils \
		dkms \
		font-manager \
		ghcup-hs-bin \
		lightdm \
		lightdm-gtk-greeter \
		linux-headers \
		pavucontrol \
		polybar \
		ttf-material-design-icons-webfont \
		xorg \
		xorg-xinit \
    alacritty \
    arandr \
    brightnessctl \
    cargo \
    cmake \
    discord \
    elixir \
    feh \
    firefox \
    flameshot \
    gcc \
    ghc \
    i3-wm \
    man-db \
    neofetch \
    network-manager-applet \
    noisetorch \
    noto-fonts-emoji \
    openvpn \
    picom \
    rofi \
    rtl8821au-dkms-git \
    rustup \
    spotify \
    texlive-full \
    ttf-google-fonts-git \
    ttf-iosevka \
    unzip \
    vim \
    vim-plug \
    visual-studio-code-bin \
    wget \
    xournalpp \
    zotero \
