#!/bin/bash

yay -Syu \
		alsa-utils \
		bluez-git \
		dkms \
		font-manager \
		ghcup-hs-bin \
		lightdm \
		lightdm-gtk-greeter \
		linux-headers \
		neovim \
		nvim-packer-git \
		pavucontrol \
		polybar \
		ttf-material-design-icons-webfont \
		xorg-server \
		xorg-xinit \
    adobe-source-han-serif-cn-fonts \
    adobe-source-han-serif-jp-fonts \
    adobe-source-han-serif-kr-fonts \
    adobe-source-han-serif-otc-fonts\
    adobe-source-han-serif-tw-fonts \
    alacritty \
    apple-fonts \
    arandr \
    brightnessctl \
    cargo \
    cmake \
    discord \
    elixir \
    feh \
    firefox \
    flameshot \
    gcc \
    ghc \
    i3-wm \
    man-db \
    neofetch \
    neovim-web-devicons-git \
    network-manager-applet \
    noisetorch \
    noto-fonts-emoji \
    openvpn \
    picom \
    pulseaudio-bluetooth \
    rofi \
    rtl8821au-dkms-git \
    rustup \
    spotify \
    ttf-iosevka \
    typst \
    unzip \
    vim \
    visual-studio-code-bin \
    wget \
    xclip \
    xournalpp \
    zotero \
