#!/bin/bash

yay -Syu --needed --color always \
    alsa-utils \
    bluez-git \
    dkms \
    font-manager \
    ghcup-hs-bin \
    lightdm \
    lightdm-gtk-greeter \
    linux-headers \
    neovim \
    nvim-packer-git \
    pavucontrol \
    polybar \
    ttf-material-design-icons-webfont \
    xorg-server \
    xorg-xinit \
    adobe-source-han-serif-cn-fonts \
    adobe-source-han-serif-jp-fonts \
    adobe-source-han-serif-kr-fonts \
    adobe-source-han-serif-otc-fonts\
    adobe-source-han-serif-tw-fonts \
    alacritty \
    arandr \
    biber \
    bitwarden \
    brightnessctl \
    cargo \
    cmake \
    discord \
    elixir \
    feh \
    firefox \
    flameshot \
    gcc \
    ghc \
    gnome-keyring \
    i3-wm \
    inter-font \
    man-db \
    mupdf \
    neofetch \
    neovim-web-devicons-git \
    network-manager-applet \
    noisetorch \
    noto-fonts-emoji \
    openssh-askpass \
    openvpn \
    picom \
    pulseaudio-bluetooth \
    rofi \
    rustup \
    spotify \
    texlive-basic \
    texlive-bibtexextra \
    texlive-fontsextra \
    texlive-fontsrecommended \
    texlive-langportuguese \
    texlive-latex \
    texlive-latexextra \
    texlive-latexrecommended \
    texlive-luatex \
    texlive-mathscience \
    texlive-plaingeneric \
    thunderbird \
    ttf-iosevka \
    typst \
    unzip \
    vim \
    visual-studio-code-bin \
    wget \
    xclip \
    zotero \
